---
title: 'Assignment 1: Introduction'
author: "Kelsie Roberton"
output:
  pdf_document: default
  word_document: default
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Lima_A01_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: No formal training with R. However, I have used Git for a past class and Python. I still need more time to exercise my coding skills. The only data analytics software I feel the most comfortable in is Excel.

2. Are there any components of the course about which you feel confident?

> Answer: Reading the data and drawing conclusions based on the information provided. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: The ability to write R code language that will be recognized for the system to perform the function I want it do. In Python, I often struggled to understand what string of code I needed to write for the software to understand what I wanted it to do. Additionally, Python was finicky with spacing and symbols. I would tend to miss a set of quotation marks or commas that would initiate the code to run. 

## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/kroberton/Environmental_Data_Analytics_2022


